# aws s3 configuration
backblaze.s3.endpoint=${BACKBLAZE_S3_ENDPOINT}
backblaze.s3.region=${BACKBLAZE_S3_REGION}
backblaze.s3.bucket-name=${BACKBLAZE_S3_BUCKET_NAME}
backblaze.s3.application-key=${BACKBLAZE_S3_APPLICATION_KEY}
backblaze.s3.application-key-id=${BACKBLAZE_S3_APPLICATION_KEY_ID}
backblaze.s3.worker-shared-secret=${BACKBLAZE_S3_WORKER_SHARED_SECRET}
# Video Processing
video.processing.temp-dir=${TEMP_DIR:/tmp/video-processing}
video.processing.ffmpeg-path=${FFMPEG_PATH:/usr/bin/ffmpeg}
video.processing.concurrent-jobs=2
# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#JWT configuration
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY}
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000
# CORS configuration
spring.cors.allowed-origin-patterns=${SPRING_CORS_ALLOWED_ORIGIN_PATTERNS}
# Proxy CDN
proxy.cdn.stream-url=${PROXY_CDN_STREAM_URL}
