# aws s3 configuration
backblaze.s3.endpoint=${BACKBLAZE_S3_ENDPOINT}
backblaze.s3.region=${BACKBLAZE_S3_REGION}
backblaze.s3.bucket-id=${BACKBLAZE_S3_BUCKET_ID}
backblaze.s3.bucket-name=${BACKBLAZE_S3_BUCKET_NAME}
backblaze.s3.application-key=${BACKBLAZE_S3_APPLICATION_KEY}
backblaze.s3.application-key-id=${BACKBLAZE_S3_APPLICATION_KEY_ID}
backblaze.s3.worker-shared-secret=${BACKBLAZE_S3_WORKER_SHARED_SECRET}
# Video Processing
video.processing.temp-dir=${TEMP_DIR:/tmp/video-processing}
video.processing.ffmpeg-path=${FFMPEG_PATH:/usr/bin/ffmpeg}
video.processing.concurrent-jobs=2
# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/netfliz
spring.datasource.username=root
spring.datasource.password=280301
#JWT configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000
# CORS configuration
spring.cors.allowed-origin-patterns=http://localhost:*,https://*.up.railway.app
# Proxy CDN
proxy.cdn.stream-url=${PROXY_CDN_STREAM_URL}
# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.username=netfliz
spring.data.redis.password=280301
