spring.application.name=netfliz-encoder
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
server.port=8081
# Overriding bean definition
spring.main.allow-bean-definition-overriding=true
# file upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=600MB
spring.servlet.multipart.max-request-size=600MB
spring.task.execution.pool.core-size=4
spring.task.execution.pool.max-size=8
spring.task.execution.pool.queue-capacity=100
# Logging
logging.level.root=INFO
logging.level.com.netfliz=DEBUG
# Video quality
# 1080p
video.qualities[0].name=1080p
video.qualities[0].width=1920
video.qualities[0].height=1080
video.qualities[0].video-bitrate=5000k
video.qualities[0].audio-bitrate=192k
# 720p
video.qualities[1].name=720p
video.qualities[1].width=1280
video.qualities[1].height=720
video.qualities[1].video-bitrate=3000k
video.qualities[1].audio-bitrate=128k
# 480p
video.qualities[2].name=480p
video.qualities[2].width=854
video.qualities[2].height=480
video.qualities[2].video-bitrate=1500k
video.qualities[2].audio-bitrate=128k
# 360p
video.qualities[3].name=360p
video.qualities[3].width=640
video.qualities[3].height=360
video.qualities[3].video-bitrate=800k
video.qualities[3].audio-bitrate=96k
# =======================
# Kafka Base Config
# =======================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
# =======================
# Producer
# =======================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.batch-size=16384
spring.kafka.producer.linger-ms=10
spring.kafka.producer.buffer-memory=33554432
spring.kafka.producer.compression-type=snappy
# Producer Properties
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.properties.spring.json.type.mapping=videoView:com.netfliz.encoder.model.event.VideoViewEvent
# =======================
# Consumer
# =======================
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=${spring.application.name}-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.fetch-min-size=1
spring.kafka.consumer.fetch-max-wait-ms=500
spring.kafka.consumer.max-poll-records=100
spring.kafka.consumer.max-poll-interval-ms=300000
# Consumer Properties
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.netfliz.encoder.model.event.BaseEvent
spring.kafka.consumer.properties.isolation.level=read_committed
spring.kafka.consumer.properties.spring.json.type.mapping=videoView:com.netfliz.encoder.model.event.VideoViewEvent
# =======================
# Listener
# =======================
spring.kafka.listener.ack-mode=manual
spring.kafka.listener.concurrency=3
spring.kafka.listener.poll-timeout=3000
spring.kafka.listener.type=batch
# =======================
# Admin
# =======================
spring.kafka.admin.properties.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
# =======================
# Custom Kafka Configuration
# =======================
kafka.topics.video-view=video-view-events
kafka.topics.update-movie-asset=update-movie-asset-topic
kafka.partitions=3
kafka.replication-factor=1
# =======================
# Logging
# =======================
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=WARN
logging.level.com.moviestreaming=DEBUG

